var nome = "Vinicius Benfatti";
var n1 = 5;
var n2 = 3;
var frase ="Japão é o melhor time do mundo";
//alert();
//alert(idade+idade2);
console.log(nome);
console.log(n1*n2);
console.log(frase.replace("Japão", "Brasil"));
console.log(frase.toUpperCase());
console.log(frase.toLowerCase());